customWorldBorder:
  enabled: true
  overworld: 10000
  nether: 7500
  end: 20000
lightGoldenAppleCraft:
  enabled: true
  goldUsed: 4
locatorBar:
  overworld: false
  nether: false
  end: true
enableNotchAppleCraft: false
pvp:
  overworld: true
  nether: true
  end: true
enableEnd: true
craftableCobwebs:
  enabled: true
  resultNumber: 2
allowEndCrystals: true
difficulty: #PEACEFUL, EASY, NORMAL, HARD
  overworld: HARD
  nether: HARD
  end: HARD
sleepPercentage: 100
anvilTweaks:
  enable: true
  disableTooExpensive: true
  decreaseCost: true
endReplacements:
  elytraCraftingRecipe: false
  endStoneRecipe: false
  chorusFlowerRecipe: false
  spireTrimRecipe: false
netherite:
  lootBoost: false
  upgradeRecipe: true
  dupeRecipe:
    enabled: false
    useDiamondBlocks: false
  disableArmor: false
enchantmentTweaks:
  enabled: false
  prot:
    enabled: true
    maxLevel: 3
  sharp:
    enabled: true
    maxLevel: 4
  power:
    enabled: true
    maxLevel: 4
maceLimit:
  enabled: true
  count: 2
autoRestock: false